apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - deploy.yaml
  - service.yaml
  - gateway.yaml
  - virtual-service.yaml

configMapGenerator:
  - name: feedi-nginx
    files:
      - nginx-feedi.conf
  - name: feedi-config
    files:
      - default.py

images:
  - name: ghcr.io/raynix/feedi
    newTag: v0.0.3
